# Generated by Django 5.2.8 on 2025-11-17 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_url', models.URLField()),
                ('event_image_url', models.URLField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_address', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_state', models.CharField(blank=True, max_length=50, null=True)),
                ('event_date', models.CharField(blank=True, max_length=100, null=True)),
                ('event_time', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
