# Generated by Django 5.2.8 on 2025-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
