# Generated by Django 5.2.8 on 2025-12-09 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster_app', '0002_savedevent_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedevent',
            name='event_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='savedevent',
            unique_together={('user', 'event_id')},
        ),
    ]
